# Generated by Django 4.2.23 on 2025-08-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_deck_delete_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cardFlipped',
            field=models.BooleanField(default=False),
        ),
    ]
