# Generated by Django 4.2.23 on 2025-08-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_deck_cardflipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('deck', models.CharField(max_length=100)),
            ],
        ),
    ]
