# Generated by Django 4.2.23 on 2025-08-19 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_flashcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='word',
            new_name='question',
        ),
    ]
